export {default as Header} from "./Header";
export {default as Sidebar} from "./Sidebar";
export {default as ProtectedRoute} from "./ProtectedRoute";
export {default as EmployeesTable} from "./tables/EmployeesTable";
export {default as PresentTable} from "./tables/PresentTable";
export {default as SalariesTable} from "./tables/SalariesTable";
export {default as ArchieveTable} from "./tables/ArchieveTable";
export {default as DismissTable} from "./tables/DismissTable";
export {default as Loader} from "./Loader";